import type { Metadata } from "next";
import "./globals.css";
import { Sora } from "next/font/google";
import Nav from "./components/Nav";
import TopLeftImg from "./components/TopLeftImg";
import Header from "../app/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={`page bg-site text-white bg-cover bg-no-repeat ${sora.variable} font-sora relative`}>
          <TopLeftImg />
          <Nav />
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
